[env:ksm]
platform = nordicnrf52
board = ksm1
framework = arduino
board_build.variants_dir = variants
# upload_protocol = nrfutil 
upload_protocol = jlink

monitor_speed = 115200
upload_speed = 115200
build_flags = 
	-Wno-psabi
	-std=c++1z
	-std=gnu++1z
	-O2
	-Wno-maybe-uninitialized
	-I variants/ksm1

lib_deps = 
	adafruit/Adafruit NeoPixel@1.11.0
	robtillaart/I2C_EEPROM@1.7.4
	fortyseveneffects/MIDI Library@5.0.2
	https://github.com/keysmet/Arduino_LSM6DS3

